### PR TITLE
lcrypto: make it build under windows

### PR DESCRIPTION
**Pull request by philips**
Move all of the variable definitions to the top. Builds under MS Visual Studio 2010 now.

### CODE REVIEW

**Comment by mkottman** [comment]
Is this the last pull request? I would rather merge one pull request (with a lot of commits) than merge each commit individually :)

**Comment by philips** [comment]
Last pull request for what? With this pull request it does build under windows.d

**Comment by philips** [comment]
FWIW, I thought the last pull request was enough because the MS compiler uses C89 which doesn't allow inline. But it also doesn't allow variable definitions in the body of the function...

**Comment by mkottman** [comment]
I was asking more generally with the pull requests - do you have any other new functionality in mind? I do not have currently time/resources to thoroughly test luacrypto, therefore I would like to accept pull requests less frequently - once a month would be ideal, so that I can test if all changes work as expected.

I.e. please send a pull request after a set of tested commits.

**Comment by mkottman** [comment]
Merged in commit eeee4bcf3a2dd4869c6ad1b87f867be578dab9f0

**Pull request closed without merging**
