### PR TITLE
revised build system

### PR DESCRIPTION
**Pull request by hasufell**
library is installed as module now and name untouched

small fix to tests/test.lua because one test failed ( tries to find "tests/message" instead of "message")

### CODE REVIEW

**Comment by hasufell** [comment]
luvit needs the header of luacrypto installed unless I want to use their bundled stuff

I provided install-rule for the header and a pkgconfig file

**Comment by mkottman** [comment]
Thanks for the autotools build system, I have tested it on Mac OS X and it works out of the box

**Comment by pbsurf** [comment]
Ran into a couple problems with the new build system on Debian 6: `configure` looks for lua.pc (which doesn't exist), whereas it probably should be looking for lua5.1.pc. Secondly, `make install` copies the generated library to /usr/lib, which is not in lua's default package path (the old build system copied to /usr/lib/lua/5.1/; /usr/local/lib/lua/5.1/ seems to be another popular choice).

IMHO, a complex, fragile autotools based build system is huge step backwards from the previous simple, readable 30 line Makefile.

**Comment by mkottman** [comment]
Unfortunately I do not know (_ehm_ and don't want to learn _ehm_) how to modify the autotools scripts to find alternative names of Lua. I could bring back the original makefile (and name it Makefile.simple), but you would have to modify it for every system you use it on. Or you can try the CMake build which usually gets everything right.

**Pull request merged**
