### PR TITLE
Adds crypto.seal and crypto.open functions

### PR DESCRIPTION
**Pull request by ignacio**
I saw that those were marked as "TO DO" so here they are, using EVP_Seal and EVP_Open functions.

Sadly, this pull request includes some other changes I made (support for ms compilers and some stuff) but I think that those can be removed if there is no need for them.

### CODE REVIEW

**Comment by ignacio** [comment]
It wasn't compiling on Linux. The last commit (f0581d7) fixes that.

**Comment by mkottman** [comment]
I am not sure about the rockspec. I am puzzled by the URL:

```
url = [[git://git.inconcert/lua-libraries/luacrypto.git]]
```

Are you sure this is not a private developer machine of your's? Maybe a link to GitHub would be better...

**Comment by ignacio** [comment]
Oh, yes... The rockspec is wrong, it is pointing to a private repo. Will fix
it later today.

**Comment by ignacio** [comment]
Also, I'm not so sure on the seal function returning the encrypted key length, the encrypted key and the initialization vector in the same binary chunk as the encrypted data.

I'll change the function to return those separately.

**Comment by ignacio** [comment]
Ok, the rockspec is fixed and open and seal functions were overhauled.

**Comment by ignacio** [comment]
Hi Michal. Do you think this patch is ok or you feel it needs some more work ?

**Comment by mkottman** [comment]
No, definitely OK, I just have little spare time right now, sorry for that, merging this pull request.

**Comment by ignacio** [comment]
Ok, sorry about that. Thank you very much!

**Pull request merged**
